name: cuidapet_api
description: API do Projeto Integrado (Regina Pratas) - PUC Minas
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^4.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.3
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  mysql1: ^0.20.0
  shelf: ^1.3.1
  shelf_modular: ^2.0.0
  shelf_router: ^1.1.3
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
  shelf_router_generator: ^1.0.3
  test: ^1.21.4
