name: regina_pratas_api
description: API do Projeto Integrado PUC Minas 2022 - Regina Pratas
version: 1.0.0
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bcrypt: ^1.1.3
  equatable: ^2.0.5
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_modular: ^2.0.1
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  dart_code_metrics: ^4.21.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.6
