openapi: 3.0.0
info:
  description: "API Regina Pratas"
  version: "1.0.10"
  title: "API Regina Pratas"
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: "auth"
    description: "Access to Auth"
  - name: "user"
    description: "Access to User"

paths:
  /auth/register:
    $ref: "src/auth.yaml#/components/Register"